In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('data/blockchain_transactions.csv')
df

,block_index,block_timestamp,block_miner_id,tx_id,tx_timestamp,tx_type,tx_sender,tx_recipient,tx_amount,tx_energy,block_hash,block_previous_hash,block_nonce
0,0,1.753185e+09,genesis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00a0c15fca506230353c4f5a8452da5fdbc6b4c5ad25ea...,0,886
1,1,1.753185e+09,GRID-OP-01,21eed0258f184cc8ab97382ff638b9a1,1.753185e+09,energy_delivery,GRID-OP-01,CON-12,0.185903,0.916408,00b70fbea4dcce4d9d0d654feb04081376007cefd82d86...,00a0c15fca506230353c4f5a8452da5fdbc6b4c5ad25ea...,292
2,1,1.753185e+09,GRID-OP-01,23268eea91b84e1b847115b1515c64e4,1.753185e+09,energy_payment,CON-12,PRO-05,0.185903,0.000000,00b70fbea4dcce4d9d0d654feb04081376007cefd82d86...,00a0c15fca506230353c4f5a8452da5fdbc6b4c5ad25ea...,292
3,2,1.753185e+09,GRID-OP-01,1b3cc40f30ce4fb7a5cfef36fe05e932,1.753185e+09,energy_payment,CON-17,PRO-06,0.021402,0.000000,00132c1fad72bc9f89ef47a1db11cb3f3e8d45dfc1ad07...,00b70fbea4dcce4d9d0d654feb04081376007cefd82d86...,70
4,2,1.753185e+09,GRID-OP-01,1d990f952b384f508c9b28583fc83959,1.753185e+09,energy_delivery,GRID-OP-01,CON-01,0.155347,0.745664,00132c1fad72bc9f89ef47a1db11cb3f3e8d45dfc1ad07...,00b70fbea4dcce4d9d0d654feb04081376007cefd82d86...,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10201,488,1.753192e+09,GRID-OP-01,e5278294f86a4fab802f45545d28700d,1.753192e+09,energy_delivery,GRID-OP-01,CON-10,0.054620,0.273024,0014dd895544403fa8c5ad7ac43319bdd010ca72867b38...,0026984c5663b3ed30156222e7f170f820ae66131a8f8a...,26
10202,489,1.753192e+09,GRID-OP-01,53b5e10dc15f4783a5a23c2d5a00ec5e,1.753192e+09,energy_delivery,GRID-OP-01,CON-10,0.029116,0.100238,00cde76878e13e975722e89fdb6a7d00f2746e0c1c5f78...,0014dd895544403fa8c5ad7ac43319bdd010ca72867b38...,250
10203,489,1.753192e+09,GRID-OP-01,663b9e1cde7d4a059b27ae00e0bb9bbf,1.753192e+09,energy_delivery,GRID-OP-01,CON-10,0.116817,0.566267,00cde76878e13e975722e89fdb6a7d00f2746e0c1c5f78...,0014dd895544403fa8c5ad7ac43319bdd010ca72867b38...,250
10204,489,1.753192e+09,GRID-OP-01,d7dc9b90c3df4f6fb2efa4156c3e841b,1.753192e+09,energy_payment,CON-10,PRO-02,0.029116,0.000000,00cde76878e13e975722e89fdb6a7d00f2746e0c1c5f78...,0014dd895544403fa8c5ad7ac43319bdd010ca72867b38...,250
10205,489,1.753192e+09,GRID-OP-01,e5a926819c7f4d66a2a75fd06b085467,1.753192e+09,energy_payment,CON-10,PRO-06,0.116817,0.000000,00cde76878e13e975722e89fdb6a7d00f2746e0c1c5f78...,0014dd895544403fa8c5ad7ac43319bdd010ca72867b38...,250

In [8]:
df.describe()

,block_index,block_timestamp,tx_timestamp,tx_amount,tx_energy,block_nonce
count,10206.000000,1.020600e+04,1.020500e+04,10205.000000,10205.000000,10206.000000
mean,243.360768,1.753188e+09,1.753188e+09,0.178276,0.445437,261.149422
std,140.788100,2.058512e+03,2.058298e+03,0.131802,0.635558,251.152467
min,0.000000,1.753185e+09,1.753185e+09,0.002200,0.000000,0.000000
25%,122.000000,1.753187e+09,1.753187e+09,0.077414,0.000000,89.000000
50%,240.000000,1.753188e+09,1.753188e+09,0.152675,0.041013,188.000000
75%,366.000000,1.753190e+09,1.753190e+09,0.247467,0.761700,365.000000
max,489.000000,1.753192e+09,1.753192e+09,1.015370,4.882501,1564.000000